spring:
  redis:
    host: 127.0.0.1 #连接地址
    port: 9999 #连接端口
    database: 0 #Redis数据库索引（默认为0）
    timeout: 1800000 #在关闭客户端连接之前等待任务处理完成的最长时间，在这之后，无论任务是否执行完成，都会被执行器关闭，默认100ms
    lettuce:
      pool:
        max-active: 20 #连接池最大连接数，设置为0或负值时，表示没有限制,默认8
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5 #连接池最大空闲连接，默认8
        min-idle: 0 #连接池中的最小空闲连接，默认0
    password: 123456 #连接密码
server:
  port: 1234
